### ISSUE TITLE
What to do after entering IP and reloading?

### ISSUE THREAD

**Issue by positron96** [gaug-cns/ros-control-center#24]
I entered IP address of the robot, went to Control tag, reloaded the page, but nothing changed.

rosbridge is running fine and other app (namely, this: http://labrom.eesc.usp.br/rosweb/) can connect to it with no problem. 

Does this app connect to a robot from the server or from browser?

**Comment by pantor** [comment]
The ROS Control Center works from the browser, so it should connect easily in principle.

Are there any errors in the console output?

**Comment by positron96** [comment]
Nevermind, I figured out what the problem was. The page was loaded from HTTPS and chrome does not want to connect to unsecured servers from secured page. In chrome console there was:

`
DOMException: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.
    at Ros.connect (https://pantor.github.io/ros-control-center/assets/js/roslib.js:1562:26)
    at new Ros (https://pantor.github.io/ros-control-center/assets/js/roslib.js:1541:10)
    at ControlController.newRosConnection (https://pantor.github.io/ros-control-center/assets/js/roscc.js:103:13)
    at ControlController (https://pantor.github.io/ros-control-center/assets/js/roscc.js:33:10)
    at Object.invoke (https://pantor.github.io/ros-control-center/assets/js/vendor.js:6552:19)
    at $controllerInit (https://pantor.github.io/ros-control-center/assets/js/vendor.js:12415:34)
    at nodeLinkFn (https://pantor.github.io/ros-control-center/assets/js/vendor.js:11295:35)
    at https://pantor.github.io/ros-control-center/assets/js/vendor.js:11703:13
    at processQueue (https://pantor.github.io/ros-control-center/assets/js/vendor.js:18381:37)
    at https://pantor.github.io/ros-control-center/assets/js/vendor.js:18425:27
(anonymous) @ vendor.js:16074
(anonymous) @ vendor.js:12557
(anonymous) @ vendor.js:11709
processQueue @ vendor.js:18381
(anonymous) @ vendor.js:18425
$digest @ vendor.js:19520
$apply @ vendor.js:19818
(anonymous) @ vendor.js:15808
defaultHandlerWrapper @ vendor.js:5283
eventHandler @ vendor.js:5271
`

I changed link from https:// to http:// and it worked. So, consider changing link in readme to unsecured veriant.

**Comment by pantor** [comment]
Thanks, I'll do that.

**Comment by nageshpindi** [comment]
> The ROS Control Center works from the browser, so it should connect easily in principle.
> 
> Are there any errors in the console output?
doesn't it works without browser....? It is working fine with browser. But its not working locally. I need clarification for that. Can u give me reply as soon as possible.
