### ISSUE TITLE
Error On Start Up

### ISSUE THREAD

**Issue by glebshevchukk** [gaug-cns/ros-control-center#25]
I'm getting the following error from the rosbridge server when I try to start up ros-control center. Can you help me figure out what causes this issue?

`['Traceback (most recent call last):\n', '  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 623, in _handle_request\n    response = convert_return_to_response(self.handler(request), self.response_class)\n', '  File "/opt/ros/indigo/lib/rosapi/rosapi_node", line 135, in get_message_details\n    typedefs = [dict_to_typedef(d) for d in objectutils.get_typedef_recursive(request.type)]\n', '  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosapi/objectutils.py", line 78, in get_typedef_recursive\n    return _get_typedefs_recursive(type, [])\n', '  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosapi/objectutils.py", line 169, in _get_typedefs_recursive\n    typedef = get_typedef(type)\n', '  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosapi/objectutils.py", line 60, in get_typedef\n    instance = ros_loader.get_message_instance(type)\n', '  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosbridge_library/internal/ros_loader.py", line 101, in get_message_instance\n    cls = get_message_class(typestring)\n', '  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosbridge_library/internal/ros_loader.py", line 88, in get_message_class\n    return _get_msg_class(typestring)\n', '  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosbridge_library/internal/ros_loader.py", line 128, in _get_msg_class\n    return _get_class(typestring, "msg", _loaded_msgs, _msgs_lock)\n', '  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosbridge_library/internal/ros_loader.py", line 154, in _get_class\n    modname, classname = _splittype(typestring)\n', '  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosbridge_library/internal/ros_loader.py", line 209, in _splittype\n    raise InvalidTypeStringException(typestring)\n', 'InvalidTypeStringException:  is not a valid type string\n']
`

**Comment by DavidTorresOcana** [comment]
I have got the same error. Any progress?

Regards

**Comment by ENGINEERDK** [comment]
Try installing full ROS bridge suite.

rosbridge_suite
